### ISSUE TITLE
Ballast does not show up in game

### ISSUE THREAD

**Issue by htomserveaux** [cmdrads/ImprovedSeaDragon#1]
the files for it are present, but no matter what I do to the .cfg i can't get it to appear.

**Comment by cmdrads** [comment]
yeah I've encountered this as well during testing sadly. I believe it's either an issue with the animation partmodule playing up, or an issue with shader definitions when exporting, as I had similar issues before due to a similar problem.

I will get onto fixing it

**Comment by Raptor22a** [comment]
The thrust vector control engines also aren't present. I can tell that this mod is - or, will - have them, as there's a thumbnail image of it included in the files. 

So far, this Sea Dragon has proved to be INCREDIBLY unruly to control, as it wants to end up flipping around for no discernable reason. Some proper thrust vectoring vernier engines would certainly help a ton in controlling it.

**Comment by cmdrads** [comment]
> 

the TVC engines are the J-2 from BDB, I stated this on the forum post

**Comment by Raptor22a** [comment]
> > 
> 
> the TVC engines are the J-2 from BDB, I stated this on the forum post

Your page on SpaceDock did not include any link to a forum page, so I was unable to find this information. I guess I know now, but perhaps when you upload the next version that fixes the ballast (now that you've marked it as closed, I assume you've fixed it), perhaps you could put the link to the forum page on there for people to be able to find.
